# Generated by Django 5.1.7 on 2025-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pizza_type', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
